apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tlsstore.yaml

secretGenerator:
  - name: default-certificate
    type: kubernetes.io/tls
    options:
      disableNameSuffixHash: true
    files:
    - tls.crt=default.crt
    - tls.key=default.key
